# Exception handling

try:
    print(f"Output: {int(input('Enter number 1: ')) / int(input('Enter number 2: '))}")
except Exception as e:
    print("Error occurred.")
